# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{watircuke}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rich Downie"]
  s.date = %q{2010-03-25}
  s.description = %q{Test Multiple Browsers with English}
  s.email = %q{rich@richdownie.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "README",
     "Rakefile",
     "VERSION",
     "features/.DS_Store",
     "features/sample.feature",
     "features/step_definitions/watircuke_steps.rb",
     "features/support/env.rb",
     "features/support/paths.rb",
     "features/support/watircuke.rb",
     "watircuke.gemspec"
  ]
  s.homepage = %q{http://github.com/richdownie/watircuke}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Cross-Browser automated testing with Cucumber and Watir}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<commonwatir>, [">= 1.6.5"])
      s.add_runtime_dependency(%q<firewatir>, [">= 1.6.5"])
      s.add_runtime_dependency(%q<safariwatir>, [">= 0.3.7"])
      s.add_runtime_dependency(%q<cucumber>, [">= 0"])
    else
      s.add_dependency(%q<commonwatir>, [">= 1.6.5"])
      s.add_dependency(%q<firewatir>, [">= 1.6.5"])
      s.add_dependency(%q<safariwatir>, [">= 0.3.7"])
      s.add_dependency(%q<cucumber>, [">= 0"])
    end
  else
    s.add_dependency(%q<commonwatir>, [">= 1.6.5"])
    s.add_dependency(%q<firewatir>, [">= 1.6.5"])
    s.add_dependency(%q<safariwatir>, [">= 0.3.7"])
    s.add_dependency(%q<cucumber>, [">= 0"])
  end
end

